FROM jenkins/jenkins:lts-jdk17

USER root

# Install Docker CLI and Compose plugin
RUN apt-get update && \
    apt-get install -y maven docker.io curl && \
    curl -SL https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose && \
    chmod +x /usr/local/bin/docker-compose

# (Optional) verify it's installed
RUN docker-compose --version

# You can switch back to jenkins user if needed
# USER jenkins