server:
  port: 8080
spring:
  application:
    name: TaskManager
  datasource:
    url: jdbc:mysql://localhost:3307/taskdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    root: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{0}: %msg%n"