# This configuration file is for test purposes only.
server:
  port: 8080
spring:
  application:
    name: task-service
  datasource:
    url: jdbc:mysql://localhost:3307/taskdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

app-key: 1i20hBJJioBo===ebw01920hONeoibno1=nOblfnfjk31wnoknjno
