server:
  port: 8080
spring:
  application:
    name: task-service
  datasource:
    url: jdbc:mysql://localhost:3307/taskdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app-key: ${APP_KEY}
kafka-task-topic: task-events